from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
from datetime import datetime,date


class Customer(BaseModel):
    customer_id: str = Field(description="The unique identifier for the customer")
    name: str = Field(description="The name of the customer")
    email: str = Field(description="The email address of the customer")
    phone: str = Field(description="The phone number of the customer")

class Items(BaseModel):
    sku: str = Field(description="The unique identifier for the item")
    name: str = Field(description="The name of the item")
    category: str = Field(description="The category of the item")
    size: str = Field(description="The size of the item")
    qty: int = Field(description="The available quantity of the item")
    price: float = Field(description="The price of the item")
    final_sale: bool = Field(description="Indicates if the item is a final sale item")
    backorder_eta: Optional[datetime] = None
    shipped: Optional[bool] = None

class Orders(BaseModel):
    order_id: str = Field(description="The unique identifier for the order")
    customer_id: str = Field(description="The unique identifier for the customer who placed the order")
    status: str = Field(description="The current status of the order")
    placed_at: datetime = Field(description="The date and time when the order was placed")
    delivered_at: Optional[datetime] = None
    expected_delivery: Optional[datetime] = None
    carrier: Optional[str] = None
    tracking_number: Optional[str] = None
    payment_method: str = Field(description="The payment method used for the order")
    shipping_city: str = Field(description="The city where the order is being shipped")
    items: List[Items] = Field(description="A list of items included in the order")
    total : float = Field(description="The total amount for the order")
    cancelled_at: Optional[datetime] = None
    refund_status: Optional[str] = None



class ChatResponse(BaseModel):
    reply: str = Field(description="The response generated by the chat model")
    escalated: bool = Field(description="Indicates if the conversation needs to be escalated to a human agent")

class ChatRequest(BaseModel):
    session_id: str = Field(description="The unique identifier for the chat session")
    message: str = Field(description="The message sent by the customer to the chat model")

class ToolResult(BaseModel):
    status : bool = Field(description="Indicates if the tool execution was successful")
    message : str = Field(description="The message returned by the tool execution")
    data : Any | None = Field(description="The data returned by the tool execution, if any")