from typing import List, Dict, Any
from pydantic import BaseModel, Field
from datetime import datetime,date


class Customer(BaseModel):
    customer_id: str = Field(description="The unique identifier for the customer")
    name: str = Field(description="The name of the customer")
    email: str = Field(description="The email address of the customer")
    phone: str = Field(description="The phone number of the customer")

class Items(BaseModel):
    sku: str = Field(description="The unique identifier for the item")
    name: str = Field(description="The name of the item")
    category: str = Field(description="The category of the item")
    size: str = Field(description="The size of the item")
    qty: int = Field(description="The available quantity of the item")
    price: float = Field(description="The price of the item")
    final_sale: bool = Field(description="Indicates if the item is a final sale item")
    backorder_eta: datetime = Field(description="The estimated time for backorder items")
    shipped : bool = Field(description="Indicates if the item has been shipped")

class Orders(BaseModel):
    order_id: str = Field(description="The unique identifier for the order")
    customer_id: str = Field(description="The unique identifier for the customer who placed the order")
    status: str = Field(description="The current status of the order")
    placed_at: datetime = Field(description="The date and time when the order was placed")
    delivered_at: datetime = Field(description="The date and time when the order was delivered")
    expected_delivery: datetime = Field(description="The expected delivery date and time for the order")
    carrier: str = Field(description="The carrier responsible for delivering the order")
    tracking_number: str = Field(description="The tracking number for the order")
    payment_method: str = Field(description="The payment method used for the order")
    shipping_city: str = Field(description="The city where the order is being shipped")
    items: List[Items] = Field(description="A list of items included in the order")
    total : float = Field(description="The total amount for the order")
    cancelled_at: datetime = Field(description="The date and time when the order was cancelled")
    refund_status: str = Field(description="The status of the refund for the order")



class ChatResponse(BaseModel):
    reply: str = Field(description="The response generated by the chat model")
    escalated: bool = Field(description="Indicates if the conversation needs to be escalated to a human agent")

class ChatRequest(BaseModel):
    session_id: str = Field(description="The unique identifier for the chat session")
    message: str = Field(description="The message sent by the customer to the chat model")

class ToolResult(BaseModel):
    status : bool = Field(description="Indicates if the tool execution was successful")